services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures for development environment
  WechatMiniProgramTrackingBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    autowire: true
    autoconfigure: true