services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures for test environment
  WechatMiniProgramTrackingBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    autowire: true
    autoconfigure: true